### ISSUE TITLE
原生部署-文档里没提到的部署方式，适合windows新人

### ISSUE THREAD

**Issue by yiyungent** [yiyungent/QQBotHub#10]
选择releases，找到并下载QQBotHub，windows系统，下载windows-64版本的即可，解压里面有exe，运行它即可，黑窗口中会显示一个url地址，复制到浏览器中打开即可，保持此黑窗口在后台运行，机器人就不会掉线

**Comment by padoru233** [comment]
url地址打开后显示“PluginCore.AspNetCore.Authentication.PluginCoreAuthenticationHandler[12]
      AuthenticationScheme: PluginCore.Authentication was challenged.”请问怎么解决

**Comment by yiyungent** [comment]
先登录 /PluginCore/Admin，readme里面有写

**Comment by padoru233** [comment]
我用域名/PluginCore/Admin也无法登陆，浏览器打开后是HTTP ERROR 502，请问是不是部署环境的问题，服务器是windows server 2012 R2

**Comment by yiyungent** [comment]
> 

访问 域名/plugincore/admin 也是502吗？把这时候的黑窗口内的报错error贴出来
