### ISSUE TITLE
QQStatPlugin 插件使用

### ISSUE THREAD

**Issue by Jv0id** [yiyungent/QQBotHub#4]
登录插件页面 出现插件的前端文件应当放在 wwwroot 文件夹下，还有哪些地方需要设置吗？

**Comment by Jv0id** [comment]
那些折线图是在哪个页面啊？我没有看到。

**Comment by Jv0id** [comment]
> > 登录插件页面 出现插件的前端文件应当放在 wwwroot 文件夹下，还有哪些地方需要设置吗？
> 
> 是不是 插件文档里的 前端, 没有问题啦，那个页面就是这个显示，我还没写管理页面

那些折线图是在哪个页面啊？我没有看到。

**Comment by yiyungent** [comment]
> 

在群聊里，发送 `#折线`,  我记得插件  `文档` 里有写， 估计你用的旧插件

**Comment by yiyungent** [comment]
注意, 
旧版需要将此群加入 `AdminGroups`, 此时 `AdminQQ`, 群主/管理员 都可以使用

新版加入 `ChartGroups` ，任何成员都可以使用
